### ISSUE TITLE
Error running 'gulp serve-dev' on windows after generating project

### ISSUE THREAD

**Issue by diegopolido** [johnpapa/generator-hottowel#105]
Hi, I got an error running 'gulp serve-dev' after generating the project:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (C:\SPNGFE\JuniperProduct\node_modules\express\lib\ap
plication.js:617:24)
    at Object.<anonymous> (C:\SPNGFE\JuniperProduct\src\server\app.js:50:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

what could it be?

Thanks!

![error-hottowel](https://cloud.githubusercontent.com/assets/140918/8533134/3ff6cf5e-2409-11e5-8e8b-b9c115d1295e.png)

**Comment by attilacsanyi** [comment]
There might be another running service in background which also use the 8001 port,  can be wamp,  apache or similar,  change port in hottowel gulp config to a rare one to verify there is no overlap.

**Comment by diegopolido** [comment]
Thanks!
