### ISSUE TITLE
ngLocale Error

### ISSUE THREAD

**Issue by castlefields** [johnpapa/generator-hottowel#11]
Hi Guys

The above error is a difficult nut to crack as already mentioned by John here: http://www.johnpapa.net/easy-fix-to-a-common-angular-module-error/

When I create a Hot Towel generated project it does not run, gulp serve-dev, and the browser complains that there is a module missing. For the life of me I cannot find what this is as I have followed the installation instructions to the letter.

Error Returned: https://docs.angularjs.org/error/$injector/strictdi?p0=function($provide

Can someone help please

Thanx

Marcus

**Comment by NicholasTuck** [comment]
@castlefields thanks for noting that it was a batarang problem, I just had this problem too and it was driving me nuts trying to figure it out over the past couple days. Disabling batarang reports no errors, however I will also be removing strictdi because that extension is too useful to not use.

Pasting my stack trace just for anyone else trying to google this too:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.3/$injector/strictdi?p0=function(%24provide)
    at REGEX_STRING_REGEXP (http://localhost:8100/app.js:8988:12)
    at Function.annotate [as $$annotate] (http://localhost:8100/app.js:12640:17)
    at Object.invoke (http://localhost:8100/app.js:13348:36)
    at runInvokeQueue (http://localhost:8100/app.js:13276:35)
    at http://localhost:8100/app.js:13285:11
    at forEach (http://localhost:8100/app.js:9256:20)
    at loadModules (http://localhost:8100/app.js:13266:5)
    at createInjector (http://localhost:8100/app.js:13192:11)
    at doBootstrap (http://localhost:8100/app.js:10550:20)
    at Object.bootstrap (http://localhost:8100/app.js:10571:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=ng&p1=Error%3A%20%5…%20Object.bootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Fapp.js%3A10571%3A12)
```
