### ISSUE TITLE
Cannot find where you keep your Bower packages.

### ISSUE THREAD

**Issue by ReaganStewart** [johnpapa/generator-hottowel#137]
Error: Error: Cannot find where you keep your Bower packages.
    at **Path to project**/test/node_modules/wiredep/wiredep.js:30:56
    at findBowerDirectory (**Path to project**/test/node_modules/wiredep/wiredep.js:108:27)
    at wiredep (**Path to project**/test/node_modules/wiredep/wiredep.js:37:43)
    at module.exports (**Path to project**/test/gulp.config.js:10:22)
    at Object.<anonymous> (**Path to project**/test/gulpfile.js:3:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by ssbrewster** [comment]
What steps are needed to reproduce the issue?

**Comment by silentw** [comment]
You are trying to run bower install correct? Just create the folder bower_components on the same level as node_modules.

**Comment by mobileiq66** [comment]
I ran into the same problem. The issue in my case was that Git was not installed on my machine, which caused Bower to fail. Perhaps the readme could be updated to mention the dependency on Git and installation instructions.

**Comment by johnpapa** [comment]
usually means bower did not install properly
