### ISSUE TITLE
Error on newly generated project

### ISSUE THREAD

**Issue by Martiveen** [johnpapa/generator-hottowel#185]
### Issue details

Getting several errors:
TypeError: [Test Error] Cannot create property 'message' on string 'Possibly unhandled rejection: {}'

Stack of first error:
﻿
angular.js:13711 TypeError: [Test Error] Cannot create property 'message' on string 'Possibly unhandled rejection: {}'
    at http://localhost:3000/src/client/app/blocks/exception/exception-handler.provider.js:54:25
    at processChecks (http://localhost:3000/bower_components/angular/angular.js:16250:9)
    at http://localhost:3000/bower_components/angular/angular.js:16256:25
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:17531:28)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:17344:31)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:17639:24)
    at bootstrapApply (http://localhost:3000/bower_components/angular/angular.js:1778:15)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4704:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1776:14)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1796:12) undefined
(anonymous function)	@	angular.js:13711
(anonymous function)	@	angular.js:10353
(anonymous function)	@	exception-handler.provider.js:55
$digest	@	angular.js:17346
$apply	@	angular.js:17639
bootstrapApply	@	angular.js:1778
invoke	@	angular.js:4704
doBootstrap	@	angular.js:1776
bootstrap	@	angular.js:1796
angularInit	@	angular.js:1681
(anonymous function)	@	angular.js:31165
fire	@	jquery.js:3099
fireWith	@	jquery.js:3211
ready	@	jquery.js:3417
completed	@	jquery.js:3433

I get that error 4 times. On creating a fresh project. My project is called Test

### Steps to reproduce/test case

Generate a new project and run

### Please specify which version of `generator-hottowel`, node and npm you're running

- [0.4] generator-hottowel
- [6.2.1] Node
- [3.9.3] Npm

### Affected platforms

- [ ] linux
- [ ] windows
- [ ] OS X
- [ ] other _(please specify which)_

### Which gulp command are you running ?

gulp serve-dev

**Comment by Martiveen** [comment]
This can be closed. This has something todo with the new RC of Angular.
