### ISSUE TITLE
Errors on gulp -build, gulp -serve-build

### ISSUE THREAD

**Issue by alphakanal** [johnpapa/generator-hottowel#204]
### Issue details

Gulp build or serve-build won't build the app. The build folder is created with the fonts + images subfolders.

Errors show while progress:

`
PhantomJS 2.1.1 (Windows 8 0.0.0) admin routes state of admin should work with $state.go FAILED
PhantomJS 2.1.1 (Windows 8 0.0.0) core state of dashboard should work with $state.go FAILED
PhantomJS 2.1.1 (Windows 8 0.0.0) core state should route /invalid to the otherwise (404) route FAILED
PhantomJS 2.1.1 (Windows 8 0.0.0) htSidebar directive:  "before each" hook: WorkFn for "is absent for a closed menu" FAILED
PhantomJS 2.1.1 (Windows 8 0.0.0) layout sidebar "before each" hook for "should have isCurrent() for / to return `current`" FAILED
PhantomJS 2.1.1 (Windows 8 0.0.0) layout sidebar "after each" hook: WorkFn for "should have isCurrent() for / to return `current`" FAILED

[11:12:40] 'test' errored after 3.46 s
[11:12:40] Error: karma: tests failed with code 1
    at formatError (C:\Users\Username\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\Project Folder\node_modules\orchestrator\index.js:264:8)
    at D:\Project Folder\node_modules\orchestrator\index.js:275:23
    at finish (D:\Project Folder\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (D:\Project Folder\node_modules\orchestrator\lib\runTask.js:29:3)
    at karmaCompleted (D:\Project Folder\gulpfile.js:598:7)
    at removeAllListeners (D:\Project Folder\node_modules\karma\lib\server.js:336:7)
    at Server.<anonymous> (D:\Project Folder\node_modules\karma\lib\server.js:347:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1553:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
`

### Steps to reproduce/test case

I have a new clean install of the hot towel - nothing is customized.

### Please specify which version of `generator-hottowel`, node and npm you're running

- [ 0.4.1 ] generator-hottowel
- [ 6.9.1 ] Node
- [ 3.10.8 ] Npm

### Affected platforms

- [ ] linux
- [ x] windows
- [ ] OS X
- [ ] other _(please specify which)_

### Which gulp command are you running ?
gulp build, gulp serve-build

**Comment by mikemead** [comment]
I had the same issue and it was resolved by https://github.com/johnpapa/generator-hottowel/pull/203

**Comment by alphakanal** [comment]
Awesome - works fine, thank you!
