### ISSUE TITLE
Question : Not working in Windows7

### ISSUE THREAD

**Issue by idefy** [johnpapa/generator-hottowel#57]
I have reinstalled it several time and always get this error in windows7 when running test or serve-build:
```
[08:36:22] Error: karma: tests failed with code 1
  at formatError (C:\Users\iadefa\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
  at Gulp.<anonymous> (C:\Users\iadefa\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (D:\personal\bitbucket\hottowel\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
  at D:\personal\bitbucket\hottowel\node_modules\gulp\node_modules\orchestrator\index.js:275:23
  at finish (D:\personal\bitbucket\hottowel\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
  at cb (D:\personal\bitbucket\hottowel\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
  at karmaCompleted (D:\personal\bitbucket\hottowel\gulpfile.js:597:13)
  at removeAllListeners (D:\personal\bitbucket\hottowel\node_modules\karma\lib\server.js:220:7)
  at Server.<anonymous> (D:\personal\bitbucket\hottowel\node_modules\karma\lib\server.js:231:9)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1392:10
  at process._tickCallback (node.js:355:11)
```
Earlier I can see that some test are failing:
```
[1A[2K[31mPhantomJS 1.9.7 (Windows 7) ShellController Shell controller should show splash screen FAILED[39m
	AssertionError: expected undefined to be true
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:873
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:1176
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:3549
PhantomJS 1.9.7 (Windows 7): Executed 35 of 39[31m (1 FAILED)[39m (0 secs / 0.118 secs)
[1A[2K[31mPhantomJS 1.9.7 (Windows 7) ShellController Shell controller should hide splash screen after timeout FAILED[39m
	[hottowel Error] expected undefined to be false
	AssertionError: expected undefined to be false
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:873
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:1201
	    at D:/personal/bitbucket/hottowel/node_modules/chai/chai.js:3549
PhantomJS 1.9.7 (Windows 7): Executed 36 of 39[31m (2 FAILED)[39m (0 secs / 0.119 secs)
```
I have installed exactly as described in the guide except node is not installed with chocolatey, I have it already installed.
What am I doing wrong ?

**Comment by ChrisHolcomb** [comment]
The test failed for me to, I just removed the test from the gulp serve-build.

**Comment by idefy** [comment]
This I could do, but then I won't have tests executing, which is not what I want. 
I believe these tests are here for a reason, so I'd rather fix these issues. But I can't seem to find the source of the problem.

**Comment by johnpapa** [comment]
LOL. test failed, so you removed it :)

I'll take a look and see why its failing and fix it.

**Comment by johnpapa** [comment]
now fixed in 0.2.10

**Comment by idefy** [comment]
Now tests pass ! thanks !

**Comment by ChrisHolcomb** [comment]
Ya, that works much better then removing the test ;)

**Comment by nikhilgoswami** [comment]
@johnpapa How did you fix it ?
