### ISSUE TITLE
Error when running gulp build

### ISSUE THREAD

**Issue by koshuang** [johnpapa/generator-hottowel#60]
When I try to build on my remote server, it fails to build with following log, does anyone how to solve this problem ?

```
# gulp build                                                                                                           [16:35:46]
[16:35:54] Using gulpfile /opt/www/cc-client/releases/20150318143521/gulpfile.js
[16:35:54] Starting 'wiredep'...
[16:35:54] Wiring the bower dependencies into the html
[16:35:54] Starting 'clean-styles'...
[16:35:54] Cleaning: ./.tmp/**/*.css,./build/styles/**/*.css
[16:35:54] Starting 'clean-code'...
[16:35:54] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[16:35:54] Starting 'vet'...
[16:35:54] Analyzing source with JSHint and JSCS
[16:35:55] Starting 'clean-images'...
[16:35:55] Cleaning: ./build/images/**/*.*
[16:35:55] Starting 'clean-fonts'...
[16:35:55] Cleaning: ./build/fonts/**/*.*
[16:35:55] Finished 'clean-images' after 12 ms
[16:35:55] Starting 'images'...
[16:35:55] Compressing and copying images
[16:35:57] Finished 'clean-fonts' after 2.22 s
[16:35:57] Starting 'fonts'...
[16:35:57] Copying fonts
[16:35:57] Finished 'clean-styles' after 3.19 s
[16:35:57] Starting 'styles'...
[16:35:57] Compiling Less --> CSS
[16:35:58] Finished 'clean-code' after 3.68 s
[16:35:58] Starting 'templatecache'...
[16:35:58] Creating an AngularJS $templateCache

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by jmlivingston** [comment]
I was also seeing the same problem and resolved it by updating gulp-ng-annotate. I changed the version in package.json to 0.5.2 and then ran an "npm install".

**Comment by johnpapa** [comment]
that worked for a few folks and we just merged a PR for that update
