### ISSUE TITLE
bower ECMDERR  when running 'yo hottowel helloWorld'

### ISSUE THREAD

**Issue by break9** [johnpapa/generator-hottowel#96]
I am sure I am the only one experiencing this, but I wondered if anyone had insight into why it happened

bower ECMDERR       

Failed to execute "gulp wiredep", exit code of #1 /Users/{me}/testsite/node_modules/lodash/dist/lodash.js:4726 });  

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/trevorallen/testsite/node_modules/browser-sync/node_modules/dev-ip/lib/dev-ip.js:13:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by break9** [comment]
had some drama with npm. was able to reinstall npm, then re-run 'yo hottowel' without issue
